# Project information
site_name: !ENV [MKDOCS_SITE_NAME, "Geotribu"]
site_description: >-
  Independent and collaborative website on free and open-source geomatics.
  Articles, tutorials, about geographic information, GIS, mapping, data visualization...

site_author: !ENV [MKDOCS_SITE_AUTHOR, "Geotribu"]
site_url: !ENV [MKDOCS_SITE_URL, "https://blog.geotribu.net/"]
copyright:
  !ENV [MKDOCS_SITE_COPYRIGHT, '<span class="copyleft">&copy;</span> Geotribu']

# Repository
repo_name: !ENV [GITHUB_REPOSITORY, "geotribu/english-blogs"]
repo_url: !ENV [MKDOCS_REPO_URL, "https://github.com/geotribu/english-blogs"]
edit_uri: !ENV [MKDOCS_EDIT_URI, "edit/main/content"]

# Custom folder structure
docs_dir: !ENV [MKDOCS_SOURCE_DIR, "./content"]
site_dir: !ENV [MKDOCS_OUTPUT_DIR, "./build/mkdocs/site"]

# Plugins
plugins:
  - blog:
      archive_name: By dates
      archive_url_date_format: yyyy/MM
      archive_url_format: "{date}"
      authors_file: "{blog}/.authors.yml"
      authors_profiles: true
      draft_on_serve: true
      draft_if_future_date: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
  - glightbox:
      auto_caption: true
      caption_position: bottom
      draggable: true
      effect: zoom
      height: auto
      skip_classes:
        - img-rdp-news-thumb
        - emojione
        - twemoji
      touchNavigation: true
      width: 90%
      zoomable: true
  - privacy:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_PRIVACY, true]
      cache_dir:
        !ENV [MKDOCS_PLUGIN_PRIVACY_EXTERNAL_CACHE_DIR, .cache/plugins/privacy]
      links_attr_map:
        target: _blank
      assets_exclude:
        # mandatory - https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/
        - cdn.jsdelivr.net/npm/mathjax@3/*
        - giscus.app/*
        # geotribu
        - cdn.geotribu.fr/images/*
        - cdn.geotribu.fr/img/*
        # external
        - cdnjs.cloudflare.com/ajax/libs/twemoji/*
        - cdn.jsdelivr.net/**/*/twemoji*
        - github.com/**/*.gif
        - i.imgur.com/*
        - raw.githubusercontent.com/*
        - twemoji.maxcdn.com/*
        - upload.wikimedia.org/*
        - user-images.githubusercontent.com/**/*.gif
  - search:
      lang: en
  - social:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_SOCIAL, true]
      cache_dir: !ENV [MKDOCS_PLUGIN_SOCIAL_CACHE_DIR, .cache/plugins/social]
      cards: !ENV [MKDOCS_ENABLE_PLUGIN_SOCIAL_CARDS, true]
      cards_layout_options:
        background_color: "#00000000"
        background_image: content/theme/assets/images/geotribu/background_geotribu.png
        color: "#3e93a7"
        font_family: Ubuntu
  - rss:
      cache_dir: !ENV [MKDOCS_PLUGIN_RSS_CACHE_DIR, .cache/plugins/rss]
      categories:
        - categories
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: date
        default_timezone: Europe/Paris
        default_time: "09:09"
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_RSS, true]
      length: 50
      match_path: blog/posts/.*
      pretty_print: false
      url_parameters:
        utm_source: "rss-feed"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
  - tags:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_TAGS, true]
      tags_sort_by: !!python/name:material.plugins.tags.tag_name_casefold
      listings_sort_by: !!python/name:material.plugins.tags.item_url
  - typeset:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_TYPESET, true]

# Theme
theme:
  name: "material"
  custom_dir: "./content/theme/"
  favicon: theme/assets/images/geotribu/logo_geotribu.png

  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    code: Ubuntu Mono
    text: Ubuntu
  language: en
  logo: theme/assets/images/geotribu/logo_geotribu.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Basculer en mode clair

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: "deep orange"
      toggle:
        icon: material/weather-sunny
        name: Basculer en mode sombre

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: "deep orange"
      toggle:
        icon: material/weather-night
        name: Basculer sur le réglage système

# Customization
extra:
  comments_url: https://comments.geotribu.fr # isso url
  url_contribuer: https://contribuer.geotribu.fr/

extra_css:
  - "theme/assets/stylesheets/extra.css"

# Extensions to enhance markdown - see: https://squidfunk.github.io/mkdocs-material/getting-started/#extensions
markdown_extensions:
  - abbr
  # Admonition - https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  - attr_list
  # Footnotes - https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes
  - md_in_html
  # Metadata - https://squidfunk.github.io/mkdocs-material/extensions/metadata
  - meta
  # PyMdown extensions - https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  # https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - pymdownx.snippets:
      base_path:
        - "."
      check_paths: true
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # Permalinks - https://squidfunk.github.io/mkdocs-material/extensions/permalinks/
  - toc:
      permalink: "#"
