# see: https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.authors_file
authors:
  gallaman:
    avatar: https://avatars.githubusercontent.com/u/40383801
    description: GIS developer of fun
    name: Guilhem Allaman
    slug: guilhem-allaman
    url: https://geotribu.fr/team/guilhem-allaman/
    email: dev@guilhemallaman.net
  geotribu:
    avatar: https://raw.githubusercontent.com/geotribu/english-blog/refs/heads/main/content/theme/assets/images/geotribu/logo_geotribu.png
    description: GIS Tribe
    name: Geotribu
    slug: geotribu-team
    url: /about
    email: geotribu+en@gmail.com
  jmoura:
    avatar: https://cdn.geotribu.fr/img/internal/contributeurs/jmou.jfif
    description: GIS Watchman
    name: Julien Moura
    slug: julien-moura
    url: https://geotribu.fr/team/julien-moura/
    email: dev@ingeoveritas.com
  nicogodet:
    avatar: https://cdn.geotribu.fr/img/internal/contributeurs/ngo.webp
    description: Hydraulic enthusiast
    name: Nicolas Godet
    slug: nicolas-godet
    url: https://geotribu.fr/team/nicolas-godet/
    email: nicolas.godet@outlook.fr
  ffougeres:
    avatar: https://avatars.githubusercontent.com/u/36446612?v=4
    description: GIS Developer
    name: Florent Fougères
    slug: florent-fougeres
    url: https://geotribu.fr/team/florent-fougeres/
    email: florent.fougeres@gmail.com
  suricactus:
    avatar: https://avatars.githubusercontent.com/u/2820439?v=4
    description: Bulgaria's BG
    name: Ivan Ivanov
    slug: ivan-ivanov
    url: /about
    email: ivan.ivanov@suricactus.com
  tszczurek:
    avatar: https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender/photo_id_tsg.png
    description: GIS Enthousiast
    name: Thomas Szczurek-Gayant
    slug: thomas-szczurek-gayant
    url: https://geotribu.fr/team/thomas-szczurek-gayant/
    email: thomas.szczurek@gmail.com
